# Generated by Django 2.0.5 on 2018-05-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djomeka_app', '0004_auto_20180522_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='files',
            field=models.FileField(upload_to='media/'),
        ),
    ]
