# Generated by Django 2.0.5 on 2018-05-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djomeka_app', '0006_auto_20180524_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='files',
            field=models.FileField(upload_to='djomeka/media/media/'),
        ),
    ]
