# Generated by Django 2.0.5 on 2018-05-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djomeka_app', '0008_auto_20180524_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='files',
            field=models.FileField(upload_to='media/media/'),
        ),
    ]
